version: '3'
services:  
  git:
    container_name: git-server
    hostname: "domain or subdomain"
    ports:
      - "443:443"
      - "8080:80"
    #volumes:
    #  - "/srv/gitlab/config:/etc/gitlab"
    #  - "/srv/gitlab/logs:/var/log/gitlab"
    #  - "/srv/gitlab/data:/var/opt/gitlab"
    image: gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = 'localhost'
          gitlab_rails['smtp_port'] = 25
          gitlab_rails['smtp_domain'] = 'localhost'
          gitlab_rails['smtp_tls'] = false
          gitlab_rails['smtp_openssl_verify_mode'] = 'none'
          gitlab_rails['smtp_enable_starttls_auto'] = false
          gitlab_rails['smtp_ssl'] = false
          gitlab_rails['smtp_force_ssl'] = false
    networks:
      - net
networks:
  net:
