version: '3'

services:
  jenkins_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_server
    ports:
      - 8085:8080
      - 50000:50000
    #volumes:
    #  - jenkins_home:/var/jenkins_home
    #network_mode: host